// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbwwbejrzlzoirsbhgch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impid3diZWpyemx6b2lyc2JoZ2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzU4MzgsImV4cCI6MjA3MjkxMTgzOH0.SZSbTZEh4be8Gh3v59MpDaLpX-L2Ao13Rzgy58J7ctI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});